# Generated by Django 4.1.7 on 2023-05-19 07:52

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_userinfo_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', validators=[account.validators.MaxAvatarSizeValidator]),
        ),
    ]
