# Generated by Django 4.1.7 on 2023-03-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_record_user_id_alter_record_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tagAssignment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tagassignment'),
        ),
    ]
