# Generated by Django 4.1.7 on 2023-03-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_quote_tagassignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.record'),
        ),
    ]
