# Generated by Django 4.1.7 on 2023-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quote_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='record_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.record'),
            preserve_default=False,
        ),
    ]
