# Generated by Django 4.1.7 on 2023-03-27 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quote_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
        migrations.AddField(
            model_name='record',
            name='familiarity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
