# Generated by Django 4.1.7 on 2023-03-27 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_record_date_added_record_familiarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
