# Generated by Django 4.1.7 on 2023-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_record_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='times_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
