# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_record_times_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='times_reviewed',
            new_name='todays_num_reviewed',
        ),
        migrations.AddField(
            model_name='record',
            name='todays_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='todays_status',
            field=models.PositiveSmallIntegerField(choices=[(0, "Don't Know"), (1, 'Uncertain'), (2, 'Uncertain or Default'), (3, 'Pass')], default=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.record'),
        ),
    ]
