# Generated by Django 4.1.7 on 2023-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_times_reviewed_record_todays_num_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='todays_reviewing',
            field=models.BooleanField(default=False),
        ),
    ]
