# Generated by Django 4.1.7 on 2023-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_record_todays_reviewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='familiarity',
            field=models.FloatField(default=0),
        ),
    ]
