# Generated by Django 4.1.7 on 2023-03-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_record_familiarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='todays_num_reviewed',
            new_name='num_reviewed',
        ),
    ]
