# Generated by Django 4.1.7 on 2023-03-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_todays_num_reviewed_record_num_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='todays_reviewing',
        ),
    ]
