# Generated by Django 4.1.7 on 2023-04-17 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_record_todays_reviewing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='todays_status',
            new_name='reviewing_status',
        ),
        migrations.RemoveField(
            model_name='record',
            name='todays_hit',
        ),
        migrations.AddField(
            model_name='record',
            name='last_planed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='last_reviewed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
