# Generated by Django 4.1.7 on 2023-04-17 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_todays_status_record_reviewing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_planed',
            field=models.DateField(default=models.DateField(default=django.utils.timezone.now)),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_reviewed',
            field=models.DateField(default=models.DateField(default=django.utils.timezone.now)),
        ),
    ]
