# Generated by Django 4.1.7 on 2023-04-17 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_record_last_planed_alter_record_last_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_planed',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_reviewed',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
