# Generated by Django 4.1.7 on 2023-04-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_record_last_planed_alter_record_last_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='familiarity',
            new_name='mastery',
        ),
    ]
