# Generated by Django 4.1.7 on 2023-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_record_last_planed_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='planedAt',
            new_name='plannedAt',
        ),
    ]
