# Generated by Django 4.1.7 on 2023-05-15 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_planedat_milestone_plannedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='plannedAt',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
