# Generated by Django 4.1.7 on 2023-05-17 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_milestone_plannedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='plannedAt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
