# Generated by Django 4.1.7 on 2023-05-20 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_alter_milestone_plannedat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('user_id', 'plannedAt')},
        ),
    ]
