# To be deleted once user preference is enabled
NUM_REVIEW_RECORDS_PER_DAY = 100
# Reviewing Records Generator Params
REVIEW_TIMES_DENOMINATOR = 5
TIME_SINCE_ADDED_DENOMINATOR = 60
FAMILIARITY_INCREMENT= 0.1

REVIEW_WINDOW_SIZE = 5
LEAST_REVIEWING_SIZE = 2

STATUS_KW = 'KW'
STATUS_UC = 'UC'
STATUS_DN = 'DN'
