name: Continuous Integration

on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: update database
        run: python manage.py makemigrations && python manage.py migrate

      - name: Run Backend Tests
        run: python manage.py test
      # - run: npm ci
      # - run: npm test
